# Generated by Django 6.0.7 on 2026-07-12 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=1, verbose_name='Ограничение по полу (M/F/ANY)')),
                ('age_category', models.CharField(blank=True, max_length=5, verbose_name='Возрастная категория (CHILD/ADULT/ANY)')),
                ('min_mental_severity', models.PositiveIntegerField(default=1, verbose_name='Мин. тяжесть псих. состояния')),
                ('max_mental_severity', models.PositiveIntegerField(default=4, verbose_name='Макс. тяжесть псих. состояния')),
                ('min_physical_severity', models.PositiveIntegerField(default=1, verbose_name='Мин. тяжесть физ. состояния')),
                ('max_physical_severity', models.PositiveIntegerField(default=4, verbose_name='Макс. тяжесть физ. состояния')),
                ('priority', models.PositiveIntegerField(choices=[(1, 'Первый приоритет'), (2, 'Второй приоритет'), (3, 'Третий приоритет'), (4, 'Четвёртый приоритет'), (5, 'Пятый приоритет')], default=3, verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_rules', to='references.department', verbose_name='Отделение')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_rules', to='references.diagnosis', verbose_name='Диагноз (МКБ-11)')),
            ],
            options={
                'verbose_name': 'Правило распределения',
                'verbose_name_plural': 'Правила распределения',
                'ordering': ['priority', 'department__name'],
            },
        ),
    ]
