# Generated by Django 6.0.7 on 2026-07-12 15:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время поступления')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает распределения'), ('assigned', 'Распределён'), ('hospitalized', 'Госпитализирован'), ('rejected', 'Отказ')], default='waiting', max_length=20, verbose_name='Статус')),
                ('assignment_note', models.TextField(blank=True, verbose_name='Примечание к распределению')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Распределено (врач)')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.department', verbose_name='Назначенное отделение')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.diagnosis', verbose_name='Диагноз (МКБ-11)')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.gender', verbose_name='Пол')),
                ('mental_severity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.mentalseverity', verbose_name='Тяжесть психического состояния')),
                ('physical_severity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.physicalseverity', verbose_name='Тяжесть физического состояния')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('is_automatic', models.BooleanField(default=False, verbose_name='Автоматическое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата распределения')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_from', to='references.department', verbose_name='Из отделения')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_to', to='references.department', verbose_name='В отделение')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Лог распределения',
                'verbose_name_plural': 'Логи распределений',
                'ordering': ['-created_at'],
            },
        ),
    ]
