# Generated by Django 6.0.7 on 2026-07-12 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MentalSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('level', models.PositiveIntegerField(unique=True, verbose_name='Уровень (1-4)')),
            ],
            options={
                'verbose_name': 'Тяжесть психического состояния',
                'verbose_name_plural': 'Тяжести психических состояний',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('level', models.PositiveIntegerField(unique=True, verbose_name='Уровень (1-4)')),
            ],
            options={
                'verbose_name': 'Тяжесть физического состояния',
                'verbose_name_plural': 'Тяжести физических состояний',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код МКБ-11')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('block', models.CharField(blank=True, max_length=200, verbose_name='Блок МКБ')),
                ('chapter', models.CharField(blank=True, max_length=200, verbose_name='Класс МКБ')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='references.diagnosis', verbose_name='Родительский диагноз')),
            ],
            options={
                'verbose_name': 'Диагноз МКБ-11',
                'verbose_name_plural': 'Диагнозы МКБ-11',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отделения')),
                ('profile', models.CharField(blank=True, max_length=500, verbose_name='Профиль (диагнозы)')),
                ('gender_restriction', models.CharField(choices=[('M', 'Мужское'), ('F', 'Женское'), ('ANY', 'Смешанное')], default='ANY', max_length=3, verbose_name='Ограничение по полу')),
                ('age_category', models.CharField(choices=[('CHILD', 'Детское/Подростковое'), ('ADULT', 'Взрослое'), ('ANY', 'Любой возраст')], default='ANY', max_length=5, verbose_name='Возрастная категория')),
                ('total_beds', models.PositiveIntegerField(default=0, verbose_name='Общее кол-во коек')),
                ('occupied_beds', models.PositiveIntegerField(default=0, verbose_name='Занято коек')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('profile_diagnoses', models.ManyToManyField(blank=True, related_name='departments', to='references.diagnosis', verbose_name='Профильные диагнозы')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'ordering': ['name'],
            },
        ),
    ]
